"""empty message

Revision ID: 0146e5896c72
Revises: 341aa605ca98
Create Date: 2025-04-14 20:44:49.203961

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '0146e5896c72'
down_revision = '341aa605ca98'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('uploaded_files', schema=None) as batch_op:
        batch_op.add_column(sa.Column('iv_file', sa.LargeBinary(), nullable=False))
        batch_op.add_column(sa.Column('iv_key', sa.LargeBinary(), nullable=False))
        batch_op.drop_column('iv')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('uploaded_files', schema=None) as batch_op:
        batch_op.add_column(sa.Column('iv', postgresql.BYTEA(), autoincrement=False, nullable=False))
        batch_op.drop_column('iv_key')
        batch_op.drop_column('iv_file')

    # ### end Alembic commands ###
