"""empty message

Revision ID: 341aa605ca98
Revises: 8182e113c7b1
Create Date: 2025-04-09 14:03:33.445455

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '341aa605ca98'
down_revision = '8182e113c7b1'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('uploaded_files', schema=None) as batch_op:
        batch_op.drop_column('salt')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('uploaded_files', schema=None) as batch_op:
        batch_op.add_column(sa.Column('salt', postgresql.BYTEA(), autoincrement=False, nullable=False))

    # ### end Alembic commands ###
