"""Change store refresh to jti

Revision ID: 4598742c2f33
Revises: 5c00a797c343
Create Date: 2025-03-19 14:58:49.842509

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4598742c2f33'
down_revision = '5c00a797c343'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user_sessions', schema=None) as batch_op:
        batch_op.add_column(sa.Column('refresh_token_jti', sa.String(length=36), nullable=False))
        batch_op.drop_column('refresh_token')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user_sessions', schema=None) as batch_op:
        batch_op.add_column(sa.Column('refresh_token', sa.VARCHAR(length=1024), autoincrement=False, nullable=False))
        batch_op.drop_column('refresh_token_jti')

    # ### end Alembic commands ###
