"""empty message

Revision ID: 4f3b21af7ee9
Revises: 8a0be76dea85
Create Date: 2025-04-14 21:00:00.622644

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '4f3b21af7ee9'
down_revision = '8a0be76dea85'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('encrypted_user_key', sa.LargeBinary(), nullable=True))
        batch_op.drop_column('user_key')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('user_key', postgresql.BYTEA(), autoincrement=False, nullable=True))
        batch_op.drop_column('encrypted_user_key')

    # ### end Alembic commands ###
