"""UserSession migration

Revision ID: 52d986045fed
Revises: 1ffe389e89b3
Create Date: 2025-03-17 01:17:51.444770

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '52d986045fed'
down_revision = '1ffe389e89b3'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user_sessions', schema=None) as batch_op:
        batch_op.add_column(sa.Column('username', sa.String(length=255), nullable=False))
        batch_op.drop_column('user_id')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user_sessions', schema=None) as batch_op:
        batch_op.add_column(sa.Column('user_id', sa.VARCHAR(length=255), autoincrement=False, nullable=False))
        batch_op.drop_column('username')

    # ### end Alembic commands ###
