"""empty message

Revision ID: 8182e113c7b1
Revises: e9811a9a9e99
Create Date: 2025-04-08 01:33:15.875264

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8182e113c7b1'
down_revision = 'e9811a9a9e99'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('user_key', sa.LargeBinary(), nullable=True))
        batch_op.add_column(sa.Column('iv', sa.LargeBinary(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_column('iv')
        batch_op.drop_column('user_key')

    # ### end Alembic commands ###
