"""empty message

Revision ID: 8a0be76dea85
Revises: a1e97d7a6477
Create Date: 2025-04-14 20:58:43.021042

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8a0be76dea85'
down_revision = 'a1e97d7a6477'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('uploaded_files',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('filename', sa.String(length=255), nullable=False),
    sa.Column('mimetype', sa.String(length=100), nullable=False),
    sa.Column('file_size', sa.Integer(), nullable=False),
    sa.Column('encrypted_data', sa.LargeBinary(), nullable=False),
    sa.Column('encrypted_key', sa.LargeBinary(), nullable=False),
    sa.Column('iv_file', sa.LargeBinary(), nullable=False),
    sa.Column('iv_key', sa.LargeBinary(), nullable=False),
    sa.Column('uploaded_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('uploaded_files')
    # ### end Alembic commands ###
