"""empty message

Revision ID: a1e97d7a6477
Revises: a293638509ee
Create Date: 2025-04-14 20:55:44.283996

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a1e97d7a6477'
down_revision = 'a293638509ee'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('user_key', sa.LargeBinary(), nullable=True))
        batch_op.add_column(sa.Column('iv', sa.LargeBinary(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_column('iv')
        batch_op.drop_column('user_key')

    # ### end Alembic commands ###
