"""empty message

Revision ID: a293638509ee
Revises: 0146e5896c72
Create Date: 2025-04-14 20:49:32.190067

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = 'a293638509ee'
down_revision = '0146e5896c72'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_column('iv')
        batch_op.drop_column('user_key')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('user_key', postgresql.BYTEA(), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('iv', postgresql.BYTEA(), autoincrement=False, nullable=True))

    # ### end Alembic commands ###
