"""Change MFA secret name to hash

Revision ID: e3e0ff9baa96
Revises: 3b2891d0e38f
Create Date: 2025-03-19 15:15:05.791818

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e3e0ff9baa96'
down_revision = '3b2891d0e38f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('mfa_secret_hash', sa.String(length=255), nullable=True))
        batch_op.drop_column('mfa_secret')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('mfa_secret', sa.VARCHAR(length=255), autoincrement=False, nullable=True))
        batch_op.drop_column('mfa_secret_hash')

    # ### end Alembic commands ###
